### ISSUE TITLE
What do the colors mean?

### ISSUE THREAD

**Issue by seanswyi** [peci1/nvidia-htop#12]
I'm using the tool with colored output. What do the colors mean?

I'm getting the impression that they may refer to the amount of memory being used, but my interpretation seems inconsistent (i.e., some GPU's with 95%+ usage are red, but some others are white).

**Comment by peci1** [comment]
The colorization logic is here:

https://github.com/peci1/nvidia-htop/blob/5971c18f6b03d09aa37dfb6c43a36764fdfe719d/nvidia-htop.py#L74

So it looks both at utilization of the compute and of memory.

**Comment by seanswyi** [comment]
Thanks!
