### ISSUE TITLE
[BUG] Command length larger than 100 does not work

### ISSUE THREAD

**Issue by zhanqiuzhang** [peci1/nvidia-htop#13]
Thanks for your nice work.

I think there is a bug in the following code.
https://github.com/peci1/nvidia-htop/blob/5971c18f6b03d09aa37dfb6c43a36764fdfe719d/nvidia-htop.py#L166

The maximum command is set to be 100 and running `nvidia-htop.py -l 200` does not work.

**Comment by peci1** [comment]
Funny, I've just run in the same issue this Friday :) Thanks for reporting. Fixed in f6a843d3034db8832bf6b153fdafa4493881c513 . Release 1.0.3 containing this fix should be on PiPy shortly.
