### ISSUE TITLE
How to renew nvidia-htop every 1 secs with color?

### ISSUE THREAD

**Issue by sjhong310** [peci1/nvidia-htop#14]
If I run
```
watch -n 1 nividia-htop.py -c
```

Your function doesn't work well. (Image below)

![image](https://user-images.githubusercontent.com/65634490/126246746-b689c1c1-42fa-4f37-bff1-0e487ef29c34.png)

How do you renew nvidia-htop with color ?

**Comment by peci1** [comment]
`watch` does not render colors by default. You have to force it to do so by the `-c` option.

    watch -c -n 1 nividia-htop.py -c

Some implementations of `watch` (mostly the busybox ones) do not have this option, but Ubuntu and other "big" Linux flavors should have it.

**Comment by peci1** [comment]
If your implementation would not have `watch -c`, this workaround works always:

    while true; do text="$(nvidia-htop.py -c)"; clear; echo "$text"; sleep 1; done

**Comment by peci1** [comment]
https://github.com/peci1/nvidia-htop/commit/7b53fba618a9ece7783f1bae9d0d7ead04295849

**Comment by sjhong310** [comment]
> `watch` does not render colors by default. You have to force it to do so using the `-c` option.
> 
> ```
> watch -c -n 1 nividia-htop.py -c
> ```
> 
> Some implementations of `watch` (mostly the busybox ones) do not have this option, but Ubuntu and other "big" Linux flavors should have it.

Thank you. It works!
