### ISSUE TITLE
Miner Virus Risk? (probably unrelated, but everyone please report if you also got it)

### ISSUE THREAD

**Issue by rachel-sunrui** [peci1/nvidia-htop#17]
Hi,

After I installed the package, a malicious process appeared on the system. It is running 100% on all GPUs and will restart after I killed it. I am wondering if other people have mention this to you, especially after your recent update ?

Thank you.

**Comment by peci1** [comment]
That's weird... How did you install it? Using pip?

**Comment by peci1** [comment]
> especially after your recent update

What update do you mean? There hasn't been any source update since August '21 and no Pypi release since May '21.

**Comment by rachel-sunrui** [comment]
Thanks for your quick response. Yes. pip3 install nvidia-htop

I just wanna double check if you heard anyone having the same issue recently. I know nothing about these miner processes. I honestly have no idea why this is happening. I noticed this systemmd (double m, not systemd) running on root about 5 mins after I ran pip install. I am just trying to gather more information here.

**Comment by peci1** [comment]
No, you're the first one reporting this issue. As there hasn't been any update of this package for almost a year, it is not probable that the package itself would be the source of problems. I see much more probable your pip got hacked.

What's the output of `which pip3` (or `sudo which pip3` if you installed with sudo)?

**Comment by peci1** [comment]
That looks ok (unless some virus changed the contents of that file).

There is a similar report from 1 year ago: https://www.reddit.com/r/Ubuntu/comments/k6vmg7/systemmd_process_using_cuda_and_4gb_of_gpu_memory/ . Can you also try to figure out where is the systemmd file located and who launches it?

**Comment by peci1** [comment]
Please also try running:

    pip3 install --download-cache="/tmp/download" nvidia-htop

and compare hashes of the downloaded files with those from https://pypi.org/project/nvidia-htop/#files .

**Comment by peci1** [comment]
Also, the only dependency this program has is `termcolor`, which had its last release in 2011. `termcolor` itself has no dependencies. So it should also not be possible that one of the dependencies got hijacked.

**Comment by peci1** [comment]
I'm closing this issue. Feel free to drop a comment if you get any new insights.
