### ISSUE TITLE
Feature Request: Implement colored utilization & memory meters like `htop`

### ISSUE THREAD

**Issue by tjk213** [peci1/nvidia-htop#24]
Would love to see colored meters for both gpu compute & memory utilization, just like htop.

**Comment by peci1** [comment]
Hi, I won't invest time into this myself. But community contributions are welcome and I'll happily review them ;)

**Comment by rit628** [comment]
Hello, I'd like to work on this feature. Could you assign me to this issue?

**Comment by peci1** [comment]
Sure, feel free to work on it ;) Send a pull reqest when you're ready. Basic requirements are just to not break any existing functionality and to keep compatibility with Python 3.8 - 3.12.

**Comment by peci1** [comment]
@tjk213 Would you be interested to test the functionality added by PR #25?

**Comment by peci1** [comment]
Version 1.2.0 containing #25 has just been published on PyPi!
