### ISSUE TITLE
subprocess AttributeError: 'module' object has no attribute 'run'

### ISSUE THREAD

**Issue by autodataming** [peci1/nvidia-htop#6]
(base) [xx@L01]$ nvidia-htop.py
Traceback (most recent call last):
  File "/home/zgong/nfs/program/anaconda2/bin/nvidia-htop.py", line 51, in <module>
    processes = subprocess.run('nvidia-smi', stdout=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'

**Comment by peci1** [comment]
Hi. If I should help you with this problem, I need you to be more verbose. Just spitting out error messages is not enough.

**Comment by peci1** [comment]
The install instructions were wrong. You need to install with `pip3 install .`, not with `pip install .`. If you already installed with `pip`, first try removing the wrongly installed file. You can find it by typing `which nvidia-htop.py`.
