### ISSUE TITLE
Add a LICENSE (e.g. MIT)

### ISSUE THREAD

**Issue by penguinmenac3** [peci1/nvidia-htop#8]
**Great work!** I really like your little tool. However, it would be great, if you could add an open source LICENSE (e.g. MIT) to allow using it also in a professional environment.

Theoretically, without a license we would not be allowed to use your code even privately or modify it and do a pull request.

**Comment by peci1** [comment]
No problem, I released under my favorite BSD 3-clause.

I hope contributors @Bobholamovic, @dexteritas, @keineahnung2345, @raytroop or @budel have no objections.
