### ISSUE TITLE
error: list of process IDs must follow -p

### ISSUE THREAD

**Issue by jss367** [peci1/nvidia-htop#9]
This application seems great but I ran into an issue when trying to use it. I pip installed it per the directions but when I ran `nvidia-htop.py -l` it printed out the normal `nvidia-smi` output but then it ran into an error: `error: list of process IDs must follow -p`. Am I doing something wrong?

**Comment by peci1** [comment]
Can you post the raw output of `nvidia-smi`? This error is weird, because it seems that your nvidia-smi doesn't output the classical "No running processes found" message when there is nothing running on the GPU.

Also, have a look at #6, there was an error in the install instructions.

**Comment by jss367** [comment]
I don't have a pip3 and my pip goes to python3, so I think that's OK:
```
(tf2) [root@host nvidia-htop]# pip --version
pip 20.0.2 from /opt/conda/envs/tf2/lib/python3.7/site-packages/pip (python 3.7)
```
Here's the output from `nvidia-smi`:
```
Mon May 11 17:57:55 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
| 39%   69C    P2   163W / 250W |  10916MiB / 11175MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 23%   30C    P8     8W / 250W |    149MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2771      G   /usr/lib/xorg/Xorg                            57MiB |
|    0      3081      G   /usr/bin/gnome-shell                          82MiB |
|    0      8429      C   python                                     10763MiB |
|    1      8429      C   python                                       137MiB |
+-----------------------------------------------------------------------------+
```

**Comment by peci1** [comment]
That's weird. If you save the output you posted to a file, e.g. `FAKE_STDIN_2` and try running 

    cat FAKE_STDIN_2 | ./nvidia_htop.py -l

in the nvidia-htop directory, do you get the same error? I can't replicate that.

**Comment by jss367** [comment]
Yea, I get the same error. I did `nvidia-smi >> FAKE_STDIN_2` then `cat FAKE_STDIN_2 | ./nvidia-htop.py -l` (note it was nvidia-htop.py with a dash instead of nvidia_htop.py, but I assume this was just a typo).


<img width="594" alt="image" src="https://user-images.githubusercontent.com/3067731/81901582-c0279100-958c-11ea-9ee7-5274fad62d3a.png">

**Comment by peci1** [comment]
Hmmm. Can you edit `nvidia-htop.py`, add the following before https://github.com/peci1/nvidia-htop/blob/5762073b243fbe68f7b379031eed1ba5d8920f49/nvidia-htop.py#L135 and post the debug output here?

    print(["ps", "-o", ps_format, "-p", ",".join(pid)])
    print(pid)
    print(subprocess.run(["ps", "-o", ps_format], stdout=subprocess.PIPE))

**Comment by peci1** [comment]
The output can contain sensitive info in the process names, so please redact it before posting.

**Comment by jss367** [comment]
Here's the output from that (I didn't have to redact anything):

```
['ps', '-o', 'pid,user,%cpu,%mem,etime,command', '-p', '']
[]
CompletedProcess(args=['ps', '-o', 'pid,user,%cpu,%mem,etime,command'], returncode=0, stdout=b'  PID USER     %CPU %MEM     ELAPSED COMMAND\n   74 root      0.0  0.0       03:33 /bin/bash\n  108 root      0.0  0.0       00:00 python3 ./nvidia-htop.py -l\n  109 root      0.0  0.0       00:00 ps -o pid,user,%cpu,%mem,etime,command\n')
error: list of process IDs must follow -p
```

**Comment by peci1** [comment]
This is super weird. The exact same input file you sent does not cause any problem for me.

Could you please try running nvidia-htop.py from branch `debug_empty_pid`? I added debugging printouts which should help resolving the issue.

    git pull origin
    git checkout debug_emtpy_pid
    ./nvidia-htop.py

**Comment by jss367** [comment]
Hmm. I grabbed your branch and ran it - not sure if it printed out what you're looking for.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/3067731/81986812-86936c00-9606-11ea-83a2-162e7f316b77.png">

I don't know if this is relevant, but I'm running this inside a docker container.

**Comment by peci1** [comment]
Are you sure the `nvidia-smi` output you posted here earlier is the one from the docker container? Because the screenshot you provided indicates that line 18 (zero-based count) is

    +------------------------------------------------

Whereas in the output you provided earlier, the corresponding line is

    |    0      2771      G   /usr/lib/xorg/Xorg                            57MiB |

**Comment by jss367** [comment]
Ah, my mistake. The first `nvidia-smi` I posted was NOT from my container. I didn't realize they would be different because they're talking to the same hardware, but obviously it is different. The output from `nvidia-smi` within my container is
```
(base) [root@oicv3host nvidia-htop]# nvidia-smi
Thu May 14 22:09:09 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
| 38%   68C    P2    73W / 250W |  10916MiB / 11175MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 23%   29C    P8     8W / 250W |    149MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by peci1** [comment]
Good, almost there :) Obviously, the container can't see "outside", so it cannot get information about the processes running directly on the hardware or in different containers. I think there's no remedy for this except for running the command outside the container.

I'll fix the script to handle the situation when there are no processes but `nvidia-smi` doesn't print the usual `No running processes found`.

**Comment by peci1** [comment]
You can try the updated `master` branch. I fixed the `ps` error and added a message that inside containers you can only see processes from within them.

**Comment by jss367** [comment]
Thanks for your help. I got it to run outside the container and it works nicely.
